### ISSUE TITLE
Provide a screenshot in the README for theme

### ISSUE THREAD

**Issue by sirkitree** [backdrop-contrib/aeon5#1]
I'd love it if we had something in the guide about this too, but it would really be great to suggest adding a screenshot to any theme's README so people can get a quick look at it's intended look.

**Comment by ghost** [comment]
Good idea. Yea that should go in the example README.md and api doc too.

**Comment by docwilmot** [comment]
smart

**Comment by ghost** [comment]
something like that?
https://github.com/backdrop-contrib/aeon5/blob/1.x-1.x/README.md

**Comment by sirkitree** [comment]
Fixed in 06452505ef1649ce80e4c3fa4b988e4c435c9b0f

Thanks!
